name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Set Xcode version
      run: xcode-select —switch /Applications/Xcode_13.0.app
    - name: Get Swift version
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
