name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Set Xcode version
      run: sudo xcode-select --switch /Applications/Xcode_13.0.app
    - name: Get Swift version
      run: swift --version
    - name: Build
      run: xcodebuild -scheme GaugeProgressViewStyle -destination 'platform=iOS Simulator,OS=15,name=iPhone 11 Pro'
    - name: Run tests
      run: swift test -v
