name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    strategy:
      matrix:
        platform: ["platform=iOS Simulator,OS=15.0,name=iPhone 11 Pro", "platform=macOS,arch=x86_64", "platform=macOS,arch=x86_64,variant=Mac Catalyst"]
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Set Xcode version
      run: sudo xcode-select --switch /Applications/Xcode_13.0.app
    - name: Swift version
      run: swift --version
    - name: Run tests
      run: xcodebuild -scheme GaugeProgressViewStyle -destination '${{ matrix.platform }}' test | xcpretty
        
  documentation:
    needs: test
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: develop
    - name: Generate Documentation
      uses: SwiftDocOrg/swift-doc@master
      with:
        inputs: "Sources"
        module-name: GaugeProgressViewStyle
        output: "./docs"
    - name: Upload Documentation to Wiki
      uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
        path: "./docs"
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      
