name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@v1
      with:
        swift-version: "5.5.0"
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
